

all: descriptiva tecnica clean

descriptiva:
	pdflatex NPI_memoria_descriptiva.tex
	pdflatex NPI_memoria_descriptiva.tex

tecnica:
	pdflatex NPI_memoria_tecnica.tex
	pdflatex NPI_memoria_tecnica.tex

clean:
	rm *.out *.log *.aux *.toc
